// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env.DATABASE_URL!,
    // Used ONLY by `prisma migrate dev` to build its throwaway shadow database.
    // Never used at runtime. Must be a DIRECT (non-pooled) Neon URL — the
    // pooled `-pooler` endpoint cannot CREATE/DROP databases, which is why
    // `db push` got used instead of `migrate dev` historically.
    // Left undefined when the env var is unset, so nothing breaks without it.
    shadowDatabaseUrl: process.env.SHADOW_DATABASE_URL,
  },
});
